import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import { CartSheet } from "@/components/CartSheet";
import { QueryProvider } from "@/components/providers/QueryProvider";

const poppinsSans = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${robotoMono.variable} antialiased flex min-h-full flex-col bg-background`}
      >
        <QueryProvider>
          <Toaster position="bottom-right" />
          <CartSheet />
          <Navbar />
          <main className="grow container mx-auto px-4 py-8">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
